### ISSUE TITLE
شرایط دورکاری کامل مشاوران مدیریت و تحول دیجیتال

### ISSUE THREAD

**Issue by HadisNazari** [iranremote/awesome-iran-remote#1]
نام شرکت : شرکت مشاوره مدیریت و تحول دیجیتال آرمان حامی شریف HAAMI Digital Consultancy
وب سایت: https://haamisharif.com
مکان شرکت:  ایران، تهران / امارات،دبی
زمینه فعالیت: مشاوره تحول دیجیتال (استراتژی دیجیتال ، رهبری دیجیتال ، تحول دیجیتال منابع انسانی)/ پیاده سازی تکنولوژی های نوین 

موقعیت های شغلی : تیم های فنی و افراد متخصص در علوم داده ، مشاوران مدیریت و تحول دیجیتال ، به صورت پروژه ای بدون نیاز به حضور در دفتر

**Comment by MRezaSafari** [comment]
لطفا تعداد افراد شاغل رو هم بفرمایید.
