### ISSUE TITLE
اضافه شدن دکتر ساینا

### ISSUE THREAD

**Issue by pooooriya** [iranremote/awesome-iran-remote#14]
سلام من در دکتر ساینا مشغول بکارم ما شرایط کاریمون به شکل دورکاریه و در لیست نیست لطفا به لیست اضافه شه 
اندازه شرکت
100-150 نفر
زمینه فعالیت
خدمات درمانی، پزشکی و سلامت
نام کامل
 شرکت نوین فن آوران همراه ساینا ( دکتر ساینا )
سایت
https://www.drsaina.com/

مرسی بابت ریپو خوبت :)

**Comment by MRezaSafari** [comment]
مورد تایید است
لطفا PR ارسال کنید
