### ISSUE TITLE
افزودن شرکت "ساعیان ارتباط" به لیست

### ISSUE THREAD

**Issue by soheiltehranipour** [iranremote/awesome-iran-remote#15]
نام شرکت :
ساعیان ارتباط

مکان :
تهران ، ایران

تعداد پرسنل :
۱۱ تا ۵۰ نفر

زمینه فعالیت:
مرکز تماس، هوش مصنوعی

وبسایت:
www.senatelecom.ir

**Comment by MRezaSafari** [comment]
مورد تایید است
لطفا PR ارسال کنید
