### ISSUE TITLE
گروه طراحی و دکوراسیون حوا

### ISSUE THREAD

**Issue by amirvafaaa** [iranremote/awesome-iran-remote#17]
شرکت : طراحی و دکوراسیون داخلی

مکان :
شیراز، ایران

زمینه فعالیت:
هنر ومعماری

تعداد کارکنان:
۲ تا ۱۰ نفر

https://www.instagram.com/p/COTJO88lo8u/?utm_medium=copy_link

**Comment by MRezaSafari** [comment]
لطفا لینک آگهی های این شرکت رو ارسال بفرمایید
