### ISSUE TITLE
مدیریت ثروت هوشمند بلوط

### ISSUE THREAD

**Issue by MohammadB72** [iranremote/awesome-iran-remote#3]
وب سایت : https://balootsaving.ir/about/
لینکدین : https://www.linkedin.com/company/balootsaving/
مکان : تهران
تعداد پرسنل : ۱۱ تا ۵۰ نفر
زمینه فعالیت : فین تک

**Comment by MRezaSafari** [comment]
سلام
در وبسایت شرکت و  سایت های کاریابی چیزی در مورد فرصت دورکاری در این شرکت عنوان نشده.

اگر هست لطفا لینک آگهی یا مکان مورد نظر در وبسایت شرکت رو اعلام بفرمایید.

متشکرم.
